export const ALL_POSTS_SUCCESS = 'ALL_POSTS_SUCCESS';
export const ALL_POSTS_FAIL = 'ALL_POSTS_FAIL';

export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL';
